model_dir: run_2/

data:
  train_features_file: /content/drive/MyDrive/Data_explo/src-train.txt
  train_labels_file: /content/drive/MyDrive/Data_explo/tgt-train.txt
  eval_features_file: /content/drive/MyDrive/Data_explo/src-val.txt
  eval_labels_file: /content/drive/MyDrive/Data_explo/tgt-train.txt
  source_vocabulary: /content/drive/MyDrive/Data_explo/src-vocab.txt
  target_vocabulary: /content/drive/MyDrive/Data_explo/tgt-vocab.txt
  source_embedding:
    path: /content/drive/MyDrive/char2vec.txt
    with_header: True
    case_insensitive: True
    trainable: False
  target_embedding:
    path: /content/drive/MyDrive/char2vec.txt
    with_header: True
    case_insensitive: True
    trainable: False

train:
  save_checkpoints_steps: 1000
  train_steps: 5000
  
eval:
  eval_delay: 300
  external_evaluators: [BLEU]
  exporters: last
  scorers: bleu


# Batching
queue_size: 10000
bucket_size: 32768
world_size: 4
gpu_ranks: [0, 1, 2, 3]
batch_type: "tokens"
batch_size: 512
valid_batch_size: 8
max_generator_batches: 2
accum_count: [4]
accum_steps: [0]

# Optimization
model_dtype: "fp32"
optim: "adam"
learning_rate: 2
warmup_steps: 8000
decay_method: "noam"
adam_beta2: 0.998
max_grad_norm: 0
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: "tokens"

# Model
encoder_type: transformer
decoder_type: transformer
position_encoding: true
enc_layers: 6
dec_layers: 6
heads: 8
rnn_size: 512
transformer_ff: 2048
dropout_steps: [0]
dropout: [0.1]
attention_dropout: [0.1]
